apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-exporters-operator
  name: ibm-monitoring-exporters-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-exporters-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ibm-monitoring
        app.kubernetes.io/instance: common-monitoring
        app.kubernetes.io/managed-by: ibm-monitoring-exporters-operator
        name: ibm-monitoring-exporters-operator
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-monitoring-exporters-operator
      hostIPC: false
      hostNetwork: false
      hostPID: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: beta.kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - ppc64le
                      - s390x
      containers:
        - name: ibm-monitoring-exporters-operator
          # Replace this with the built image name
          image: quay.io/opencloudio/ibm-monitoring-exporters-operator:1.8.0
          command:
            - ibm-monitoring-exporters-operator
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              cpu: 50m
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-monitoring-exporters-operator"
            - name: ROUTER_IMAGE
              value: quay.io/opencloudio/icp-management-ingress@sha256:c7f4960f2df024cd3b43b08d115047293359478b5b91b15e9f3b8c40a3af74d3
            - name: COLLECTD_IMAGE
              value: quay.io/opencloudio/collectd-exporter@sha256:ab809994a089c51b498cef7f166612ef6472c6e5358646c66a4dcb6d14c3c489
            - name: NODE_IMAGE
              value: quay.io/opencloudio/node-exporter@sha256:78634e8f421a7e9de65a3fee153779258fe1c8f2a92a79afea5a0ef74d7c1496
            - name: KUBESTATE_IMAGE
              value: quay.io/opencloudio/kube-state-metrics@sha256:eb56f0f6d8ca5efe646f7408bf5194d1d1fa76940a5d312f704d34de0fe826f7
