apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-exporters-operator
  name: ibm-monitoring-exporters-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-monitoring-exporters-operator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ibm-monitoring
        app.kubernetes.io/instance: common-monitoring
        app.kubernetes.io/managed-by: ibm-monitoring-exporters-operator
        name: ibm-monitoring-exporters-operator
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productVersion: "3.4.0"
        productMetric: FREE
    spec:
      serviceAccountName: ibm-monitoring-exporters-operator
      hostIPC: false
      hostNetwork: false
      hostPID: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - ppc64le
                - s390x
      containers:
        - name: ibm-monitoring-exporters-operator
          # Replace this with the built image name
          image: quay.io/opencloudio/ibm-monitoring-exporters-operator:1.8.0
          command:
          - ibm-monitoring-exporters-operator
          imagePullPolicy: Always
          securityContext:
            privileged: false
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
              - ALL
          resources:
            limits:
              cpu: 50m
              memory: 512Mi
            requests:
              cpu: 20m
              memory: 64Mi
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ibm-monitoring-exporters-operator"
            - name: ROUTER_IMAGE
              value: quay.io/opencloudio/icp-management-ingress@sha256:f6694ea8a461468989874b4b091f1d64366eacb9821cc9836d8100e34f333634
            - name: COLLECTD_IMAGE
              value: quay.io/opencloudio/collectd-exporter@sha256:03a5725f69f764dd5967ecc9b1b84cd8745034bdb7dc659805f3158d9b954657
            - name: NODE_IMAGE
              value: quay.io/opencloudio/node-exporter@sha256:c6e70a339e0cde2b93c16a5640dd986fd46a5faf1e6bcf668f5feba300972c20
            - name: KUBESTATE_IMAGE
              value: quay.io/opencloudio/kube-state-metrics@sha256:eedcd7aed0ad465c7b2e151916e56013bd92356633a35fe5ab11115f2454c8ae
