---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-exporters-operator
  creationTimestamp: null
  name: ibm-monitoring-exporters-operator
rules:
- apiGroups:
  - security.openshift.io
  resources:
  - securitycontextconstraints
  verbs:
  - create
  - update
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-exporters-operator
  creationTimestamp: null
  name: ibm-monitoring-exporter
rules:
- apiGroups:
  - ""
  resources:
  - '*'
  verbs:
  - list
- apiGroups:
  - apps
  resources:
  - '*'
  verbs:
  - list
- apiGroups:
  - batch
  resources:
  - '*'
  verbs:
  - list
- apiGroups:
  - extensions
  resources:
  - '*'
  verbs:
  - list
- apiGroups:
  - networking.k8s.io
  resources:
  - '*'
  verbs:
  - list
- apiGroups:
  - storage.k8s.io
  resources:
  - '*'
  verbs:
  - list
- apiGroups:
  - autoscaling
  resources:
  - '*'
  verbs:
  - list
- apiGroups:
  - policy
  resources:
  - '*'
  verbs:
  - list
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - '*'
  verbs:
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: ibm-monitoring
    app.kubernetes.io/instance: common-monitoring
    app.kubernetes.io/managed-by: ibm-monitoring-exporters-operator
  creationTimestamp: null
  name: ibm-monitoring-exporters-operator
rules:
- apiGroups:
  - ""
  resources:
  - services
  - configmaps
  - pods
  - endpoints
  - events
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - deployments/finalizers
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - monitoring.operator.ibm.com
  resources:
  - exporters
  - exporters/finalizers
  - exporters/status
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - certmanager.k8s.io
  resources:
  - certificates
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete